#!/bin/bash

# Условный цикл while
# while [[условие]]; do
#    ...
# done
# Или в одну строку:
# while [[условие]]; do ...; done

counter=0
# Напечатаем "Hello, $counter!" пять раз
while [[ $counter -lt 5 ]]; do
    echo "Hello, $counter!"
    # Увеличим счетчик на 1
    # ((...)) позволяет использовать арифметические операции
    ((counter++))
done

# Напечатаем сами себя, используя команду read.
# Здесь не используется [[...]] или [...] для проверки условия,
# потому что read возварщает 0, когда достигнут конец файла.
# Таким одразом можно использовать команды с кодом возврата в качестве условий. 
while read line; do
    echo "Read: $line"
done < ./while-example

# Можно заранее выйти из цикла, используя команду break,
# или пропустить итерацию, используя команду continue.
# Выведется: 0 1 2 5 6
counter=0
while [[ $counter -lt 10 ]]; do
    # Используем || для логического ИЛИ условий.
    if [[ $counter -eq 3 ]] || [[ counter -eq 4 ]]; then
        ((counter++))
        continue
    fi
    if [[ $counter -gt 6 ]]; then
        break
    fi
    echo $counter
    ((counter++))
done
